### ISSUE TITLE
Support for GHC 9.0.1

### ISSUE THREAD

**Issue by sjakobi** [haskell-hvr/cryptohash-sha1#10]
The latest release excludes `base-4.15`. While a bounds bump seems sufficient to make the package compile, it might also be worth looking at other migration issues like https://gitlab.haskell.org/ghc/ghc/-/wikis/migration/9.0#withforeignptr.

**Comment by andreasabel** [comment]
I filed 
- https://github.com/haskell-infra/hackage-trustees/issues/313 
 
for the base bump.

**Comment by debug-ito** [comment]
Revision 6 now support base-4.15,

**Comment by sjakobi** [comment]
Great news! :)
