### ISSUE TITLE
Support GHC 9.2

### ISSUE THREAD

**Issue by andreasabel** [haskell-hvr/cryptohash-sha1#13]
Lifted from: 
- https://github.com/haskell-infra/hackage-trustees/issues/319

Just the _library_ builds fine on `master`.

To get build with tests and benchmarks started (as stated in `cabal.project`), try:
```
$ cabal build --allow-newer=cereal:base \
  --allow-newer=vector-th-unbox:base --allow-newer=vector-th-unbox:template-haskell \
  --allow-newer=microstache:base \
  --allow-newer=cassava:base \
  --allow-newer=aeson:{ghc-prim,template-haskell} \
  --allow-newer=hsc2hs:base
```
However, this fails on at least:
- [x] cereal (https://github.com/GaloisInc/cereal/pull/99) candidate: https://hackage.haskell.org/package/cereal-0.5.8.2/candidate
- [x] aeson (https://github.com/haskell/aeson/issues/885, https://github.com/haskell/aeson/pull/856)

**Comment by phadej** [comment]
Argh. `hsc2hs` release have been pending for ages (more correctly: a year?). Please ping on one of
- https://github.com/haskell/hsc2hs/issues/60
- https://github.com/haskell/hsc2hs/issues/61 or
- https://github.com/haskell/hsc2hs/issues/64 

it seems that I'm ignored.

**Comment by phadej** [comment]
https://hackage.haskell.org/package/cryptohash-sha1-0.11.101.0 released
