### ISSUE TITLE
Support GHC-9.6

### ISSUE THREAD

**Issue by ysangkok** [haskell-hvr/cryptohash-sha1#18]
Seems like the bounds reject the base from GHC-9.6:

```
[__5] rejecting: binary-0.8.9.1/installed-0.8.9.1 (conflict: cryptohash-sha1
=> base>=4.5 && <4.18, binary => base==4.18.0.0/installed-4.18.0.0)
```

Allow-newer seems to work so maybe a revision is sufficient.

Would be nice to also cover cryptohash-md5.

**Comment by phadej** [comment]
ping @andreasabel

**Comment by Bodigrim** [comment]
Yep, I tested `cryptohash-sha1` and `cryptohash-md5`, both are doing well with GHC 9.6. A revision would be appreciated.

**Comment by andreasabel** [comment]
Revision published!
