### ISSUE TITLE
Mismatching license headers

### ISSUE THREAD

**Issue by jinwoo** [haskell-hvr/cryptohash-sha1#6]
The LICENSE file is BSD-3 but source files, sha1.c and sha1.h, have BSD-2 copyright headers. Can this be fixed and re-released?

Thanks.

**Comment by phadej** [comment]
That's already present in https://hackage.haskell.org/package/cryptohash-0.11.7/src/cbits/sha1.h
from which this derives. So AFAICS the header cannot be changed, that file was originally under BSD-2-Clause. But the package overall can be licenses as BSD-3-Clause as the licenses are compatible. So I don't see anything wrong here.

**Comment by jinwoo** [comment]
Thanks for the clarification. Closing.
