### ISSUE TITLE
Provide support for bytestring-0.11

### ISSUE THREAD

**Issue by nikita-volkov** [haskell-hvr/cryptohash-sha1#9]

**Comment by andreasabel** [comment]
Release 0.11.102.1 supports bytestring-0.11.
I just wonder why `cabal` does not see it:
```
$ cabal install cryptohash-sha1-0.11.102.1
Resolving dependencies...
Error: cabal: Could not resolve dependencies:
[__0] next goal: cryptohash-sha1 (user goal)
[__0] rejecting: cryptohash-sha1-0.11.100.1, cryptohash-sha1-0.11.100.0,
cryptohash-sha1-0.11.7.2, cryptohash-sha1-0.11.7.1 (constraint from user
target requires ==0.11.102.1)
```
Maybe you cannot have a minor version that exceeds 100, haha!

**Comment by phadej** [comment]
> Release 0.11.102.1 supports bytestring-0.11.
I just wonder why cabal does not see it:

Because it's not on Hackage yet. https://hackage.haskell.org/package/cryptohash-sha1

**Comment by andreasabel** [comment]
Oh.
There is a very similar package https://hackage.haskell.org/package/cryptohash-sha256-0.11.102.1 with similar version numbers, so I got confused.

**Comment by phadej** [comment]
https://hackage.haskell.org/package/cryptohash-sha1-0.11.101.0 released
